[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
max-complexity = 20
ignore = "E203,E266,W503,"

[tool.isort]
line_length = 88
force_single_line = true

[tool.mypy]
ignore_missing_imports = 1
