"""empty message

Revision ID: 51fa6ed18cdc
Revises: b65dd14a2d85
Create Date: 2023-09-26 00:32:03.057314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fa6ed18cdc'
down_revision = 'b65dd14a2d85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
