"""empty message

Revision ID: 56d6096d9496
Revises: cda47829a821
Create Date: 2023-10-08 00:44:20.592285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d6096d9496'
down_revision = 'cda47829a821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
