"""empty message

Revision ID: b65dd14a2d85
Revises: 7ceaf3a114a0
Create Date: 2023-09-26 00:30:58.048881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65dd14a2d85'
down_revision = '7ceaf3a114a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
