"""empty message

Revision ID: cda47829a821
Revises: f15eccd7cd3b
Create Date: 2023-10-01 11:25:26.178102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda47829a821'
down_revision = 'f15eccd7cd3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
